volumes:
  spotify-insights-vol:

services:

  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_CONN_STRING=postgresql+psycopg://root:secret@db:5432/spotify-insights-db
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
      - POSTGRES_DB=spotify-insights-db
    volumes:
      - spotify-insights-vol:/var/lib/postgresql/data