volumes:
  spotify-insights-vol:

services:  
  
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
      - POSTGRES_DB=spotify-insights-db
    volumes:
      - spotify-insights-vol:/var/lib/postgresql/data