"""Initial

Revision ID: d90dbf6e38f7
Revises: 
Create Date: 2023-08-25 20:33:25.760162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90dbf6e38f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('spotify_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spotify_username', sa.String(length=100), nullable=False),
    sa.Column('authorization_token', sa.String(length=255), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'spotify_username'),
    sa.UniqueConstraint('spotify_username')
    )
    op.create_table('spotify_profile_saved_songs',
    sa.Column('spotify_username', sa.String(), nullable=False),
    sa.Column('song_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['spotify_username'], ['spotify_profiles.spotify_username'], ),
    sa.PrimaryKeyConstraint('spotify_username', 'song_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spotify_profile_saved_songs')
    op.drop_table('spotify_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
