"""Add refresh token to spotify_profiles

Revision ID: eafaa8acc2ac
Revises: d90dbf6e38f7
Create Date: 2023-08-26 15:04:51.170051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eafaa8acc2ac'
down_revision: Union[str, None] = 'd90dbf6e38f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_profiles', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotify_profiles', 'refresh_token')
    # ### end Alembic commands ###
