"""saved songs table

Revision ID: 1aee247875cb
Revises: 206a0ca7d905
Create Date: 2023-08-25 02:49:28.301813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aee247875cb'
down_revision: Union[str, None] = '206a0ca7d905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotify_profile_saved_songs',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['spotify_profiles.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'song_id')
    )
    op.create_unique_constraint(None, 'spotify_profiles', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spotify_profiles', type_='unique')
    op.drop_table('spotify_profile_saved_songs')
    # ### end Alembic commands ###
